function [BW,maskedImage] = segmentImage(RGB)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the imageSegmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 31-Jan-2022
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.
X = rgb2lab(RGB);

% Graph cut
foregroundInd = [278209 278213 279483 285870 285875 285878 289709 292262 292265 298657 302488 302489 308881 311438 316550 321663 322937 322939 322940 322942 326774 329332 329334 333166 333169 335722 335724 339559 342116 345953 345954 348506 348508 348511 352345 353620 353621 353623 353625 358735 358737 358738 360010 360013 363847 363849 366399 366400 366402 366404 366405 864416 868256 874656 886176 895136 901536 906656 915616 923294 932252 938652 948891 956571 965529 973209 979609 986009 993689 997529 1000089 1003929 1006489 1007768 1010328 1012888 1016726 1018006 1020566 1023126 1024406 1026966 1029526 ];
backgroundInd = [571162 581395 595464 645350 669657 676052 682451 686288 688844 693961 704195 710590 719547 723385 725943 729780 731059 736175 736177 736179 737455 ];
L = superpixels(X,6244,'IsInputLab',true);

% Convert L*a*b* range to [0 1]
scaledX = prepLab(X);
BW = lazysnapping(scaledX,L,foregroundInd,backgroundInd);

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

function out = prepLab(in)

% Convert L*a*b* image to range [0,1]
out = in;
out(:,:,1) = in(:,:,1) / 100;  % L range is [0 100].
out(:,:,2) = (in(:,:,2) + 86.1827) / 184.4170;  % a* range is [-86.1827,98.2343].
out(:,:,3) = (in(:,:,3) + 107.8602) / 202.3382;  % b* range is [-107.8602,94.4780].

end
